# Generated by Django 5.0.7 on 2024-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="text",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
