# Generated by Django 5.0.7 on 2024-07-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_stack_name_alter_stack_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stack",
            name="name",
            field=models.JSONField(default="", max_length=200),
        ),
    ]
