# Generated by Django 5.0.7 on 2024-07-13 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_stack_name_stack_stack_name_alter_stack_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stack",
            name="stack_name",
        ),
    ]
