# Generated by Django 5.0.7 on 2024-07-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_stack_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stack",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="stack",
            name="text",
            field=models.JSONField(default="{}", max_length=1000),
        ),
    ]
