# Generated by Django 5.0.7 on 2024-07-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_stack_name_alter_stack_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stack",
            name="name",
        ),
        migrations.AddField(
            model_name="stack",
            name="stack_name",
            field=models.JSONField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="stack",
            name="text",
            field=models.JSONField(default="", max_length=1000),
        ),
    ]
